// top = more recently watched
export const MOVIES: [string, number][] = [
    ["Adaptation", 8.5],
    ["Loki2", 7.5],
    ["Hadestown", 9],
    ["Loki", 7.8],
    ["Spiderman BND", 7.2],
    ["Yesterday", 7.7],
    ["Cyperpunk Edgerunners", 8.3],
    ["Millenium Actress", 7.7],
    ["Oddyssey", 7.9],
    ["Goodwill hunting", 9],
    ["Perks of being a wallflower", 8.6],
    ["Eternal Sunshine of the Spotless Mind", 8.9],
    ["The Big Short", 8.1],
    ["American Psycho", 8.3],
    ["Dr Strangelove", 8],
    ["Tenet", 7.6],
    ["Inception", 8.6],
    ["Perfect Blue", 8.9],
    ["Parasite", 8],
    ["Milk and Serial", 7.5],
    ["Harrison Bergeron", 6.5],
    ["Kiki's Delivery Service", 8],
    ["Backrooms", 7.5],
    ["Dark Knight", 7.8],
    ["Grand Budapest Hotel", 8],
    ["Obsession", 8.7],
    ["Age of Ultron", 7.2],
    ["Catch me if you can", 8.6],
    ["Michael", 7.2],
    ["Trust and Betrayal (all 4 episodes)", 8.9],
    ["Memento", 8],
    ["Truman Show", 7.9],
    ["Shawshank Redemption", 8.4],
    ["Project Hailmary", 7.9],
    ["LalaLand", 8.6],
    ["Back to the Future", 8.7],
    ["Back to the Future Part II", 7.5],
    ["Back to the Future Part 3", 7.8],
    ["WarGames", 7.4],
    ["Life is Beautiful", 8],
    ["Look Back", 7.6],
    ["The Imitation Game", 7.4],
    ["Whiplash", 8],
    ["Whisper of the Heart", 7.6],
    ["The Prestige", 8.2],
    ["Grave of the Fireflies", 9.1],
    ["Spirited Away", 8.7],
    ["Princess Mononoke", 8.3],
    ["Howl’s Moving Castle", 7.4],
    ["The Lord of the Rings (all 3)", 9],
    ["Hamilton", 8.2],
    ["Avatar 3", 7],
    ["Mission: Impossible – Final Reckoning", 6.4],
    ["The Grudge", 6],
    ["Gladiator", 7.6],
    ["Free Solo", 6],
    ["Pluto episode 1", 9],
    ["The Boys", 7.9],
    ["Frieren Sea1", 9],
    ["Berserk", 8.7],
    ["FullMetal Alchemist", 9],
    ["Frieren Sea2", 8],
];
